spring.application.name=blockchain
spring.mongodb.uri=mongodb://Piyush_Pareek_207:PPiyush%402007@ac-omg5rua-shard-00-00.lem3u4g.mongodb.net:27017,ac-omg5rua-shard-00-01.lem3u4g.mongodb.net:27017,ac-omg5rua-shard-00-02.lem3u4g.mongodb.net:27017/CorruptionCatcher?ssl=true&replicaSet=atlas-m4bfzm-shard-0&authSource=admin&appName=Piyush-Pareek-207
# --- GRAPH DATABASE SETTINGS (Neo4j AuraDB) ---
spring.neo4j.uri=neo4j+s://683ddcf3.databases.neo4j.io
spring.neo4j.authentication.username=683ddcf3
spring.neo4j.authentication.password=5cQ5ZA8I9w5rN5EWpELN0xcdx6FEUf2kRqTx5DqPv1g